name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the deployabel artifact files
        required: false
        default: dist
        type: string
    #secret:
    #  some-secret:
    #    required: true
    outputs:
      result:
        description: Result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT